# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangobin.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangobin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_logged_in',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='default_expiration',
            field=models.CharField(choices=[('never', 'Never'), ('1 week', '1 week'), ('1 month', '1 month'), ('6 month', '6 month'), ('1 year', '1 year')], default='never', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='default_exposure',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='default_language',
            field=models.ForeignKey(default=djangobin.models.get_default_language, on_delete=django.db.models.deletion.CASCADE, to='djangobin.Language'),
        ),
        migrations.AddField(
            model_name='author',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Language Code'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='highlighted_code',
            field=models.TextField(blank=True, help_text='Read only field. Will contain the syntax-highlited version of the original code.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='hits',
            field=models.IntegerField(default=0, help_text='Read only field. Will be updated after every visit to snippet.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(help_text='Read only field. Will be filled automatically.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='djangobin.Tag'),
        ),
    ]
